### ISSUE TITLE
error when trying to install -  /etc/zabbix/zabbix-agent-extension-rabbitmq is not within a known GOPATH/src

### ISSUE THREAD

**Issue by Denagar** [zarplata/zabbix-agent-extension-rabbitmq#1]
hi - first of all thanks for this extention, it would be perfect for my monitoring system. 

so i have tried to install the extention, 
i cloned the git directory, 
but when i try to run the "make" command it fails. 
i already installed go-dep. 
the error i am getting is:

> :/etc/zabbix/zabbix-agent-extension-rabbitmq# make
Clean dependencies
rm -rf vendor/*
Clean builded binaries
rm -rf .out/
Done
Fetch dependencies
dep ensure -v
/etc/zabbix/zabbix-agent-extension-rabbitmq is not within a known GOPATH/src
Makefile:35: recipe for target 'deps' failed
make: *** [deps] Error 1

am i missing anything, is there any otyher prerequesit i need ? 
thanks in advance

**Comment by tears-of-noobs** [comment]
@Denagar Hi. Be sure that this project located inside $GOPATH/src.
For example:
1. Install go lang for your Linux distribution
2. Create a project directory, $GOPATH variable and build project
 ```sh
mkdir -p ~/go/{src,bin,pkg}
export GOPATH=~/go/src
cd $GOPATH/src
git clone https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git
cd zabbix-agent-extension-rabbitmq
make
```
Of cource you can place GOPATH initialization into your .bashrc or .zshrc

**Comment by Denagar** [comment]
Perfect that worked, 
and i got all the queues discovered but no information is populated in the items. 
what am i missing?

**Comment by tears-of-noobs** [comment]
Hostname of monitored node equal with a node in Zabbix server? Be note, that this extension send hostname with metrics of a monitored node and Zabbix server determine received metrics only by hostname. Anyway, show me the value of `RabbitMQ stats` item from `Monitoring` -> `Latest data`

**Comment by Denagar** [comment]
the value shows OK, but i will verify that the node name are exactly the same.

![image](https://user-images.githubusercontent.com/33426057/51802843-8e36d200-2256-11e9-817a-4609aca481a1.png)

Edit: the Host name under /etc/hostname and in zabbix agent config and zabbix server are the same, and still no data in the items.

**Comment by tears-of-noobs** [comment]
Yeap, verify, please. It'a small exception for our extension's, all of them don't use `zabbix_sender` which reads `zabbix_agent.conf` and recognizes the `Hostname` option, our extension obtain hostname of server/VM/container directly from OS.

**Comment by Denagar** [comment]
it works !! thanks so much for your help 
amazing plugin !!!!

**Comment by cmmata** [comment]
What was the solution? I'm having the same problem as the last screen capture, I have zabbix monitoring but not receiving some data. I have checked hostname, zabbix-agent and zabbix-server name and they are all the same.

![screenshot](https://user-images.githubusercontent.com/4223148/54024267-978d5580-4197-11e9-8af6-5b84a28d5ecf.png)

Also, I have an error in discovery. I don't know if that's the problem
![screenshot2](https://user-images.githubusercontent.com/4223148/54024398-fe127380-4197-11e9-9d1a-2459bea4e1e0.png)

**Comment by adavies169** [comment]
Hi, @Denagar & @tears-of-noobs  I'm having the same problem with this extension. Zabbix has found my queues and channels but I am not getting any data from them. Would you be able to explain the fix for this please? I have checked the hostname in /etc/hostname which matches exactly in Zabbix. 

Thanks

**Comment by ericllistar** [comment]
I'm having problems discovering queues and some other data.
When I send the command in order to debug then not supported message, I received:

[t|json: cannot unmarshal string into Go struct field QueueInfo.consumer_utilisation of type float64]

Please anyone can help me?

Thanks
