### ISSUE TITLE
[FeatureRequest] {$RABBITMQ_ADDRESS} macros for remote monitoring

### ISSUE THREAD

**Issue by smith151** [zarplata/zabbix-agent-extension-rabbitmq#10]
Could you please add ability to monitor "remote" RabbitMQ by adding {$RABBITMQ_ADDRESS} macros? Now your extension asking localhost but I have rabbitmq working inside docker container. And zabbix agent working as another docker container on this host. This zabbix agent has rights to get request to rabbitmq on internal IP of docker host like 10.20.30.40. And it would be nice if zabbix rabbitmq extension ask to IP 10.20.30.40.

**Comment by tears-of-noobs** [comment]
@smith151 Hi. This macros `{$RABBITMQ_MGMT_ADDRESS}` already exists and its default behavior describes in "Configuration" section of README file [](url)https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/README.md#configuration

**Comment by smith151** [comment]
Ok, sorry. I mean to check rabbitmq processes count and so on but it can be made on rabbitmq host only. Thanks for explanation.

**Comment by tears-of-noobs** [comment]
`zabbix-agent's` built-in function - `proc.num[]` uses the `/proc` filesystem to determine the number of processes, so if you want to calculate number of running processes - you should grant read access to host `/proc` filesystem from your docker container or start `zabbix-agent` on a host without docker.
