### ISSUE TITLE
Zabbix aggregate not receiving data

### ISSUE THREAD

**Issue by adavies169** [zarplata/zabbix-agent-extension-rabbitmq#13]
Hi, 

I'm new to Zabbix and RabbitMQ so please bare with me. I've followed your instructions on getting aggregate checks. The module finds the aggregate queues, but is not receiving any data from them. I receive this error when checking the Items properties for each aggregate queue:

No values for key "rabbitmq.queue.messages[/,AlexTest]" in group(s) "AlexTest-TH-RabbitPublic"

Does anyone know what that means specifically? 

Thanks
Alex

**Comment by tears-of-noobs** [comment]
Hi, @adavies169. Please provide a little bit more information about your setup. How many nodes do you monitoring with the extension, more than one? Aggregate checks in Zabbix works on nodes in the same group, so if you want to get some data you should be confident that you have several nodes in one group. Please provide some screenshots with the problem and your configuration of aggregate items if it is possible.
