### ISSUE TITLE
Missing triggers?

### ISSUE THREAD

**Issue by igorinsky** [zarplata/zabbix-agent-extension-rabbitmq#14]
Hello, I'm referring to the part which says the extension by default has  triggers which detect following situations:
"infinity or very long redeliver" 
"zero deliver rate when queue not empty"  (really looking for this trigger, don't want to setup a custom bash script to achieve the same)

In my template only three triggers are available:
Can't obtain RabbitMQ stats
RabbitMQ Memory Alarm (publishers blocked)
RabbitMQ process is NOT running

Did I miss anything during the install process?

**Comment by tears-of-noobs** [comment]
@igorinsky Hi. Tell me a little bit more information about your installation. Have you installed RabbitMQ as a single node or you have a cluster setup?

**Comment by igorinsky** [comment]
@tears-of-noobs  Hello, It's a single node setup.

**Comment by tears-of-noobs** [comment]
@igorinsky Did you define a macro `{$GROUPNAME}` on your RabbitMQ node? If not, you should do it. Read the last paragraph of the readme. In short - Zabbix will create aggregation triggers only if you define macro `{$GROUPNAME}` with the group name where your node was added.

**Comment by igorinsky** [comment]
Not sure if I follow you. How configured\non-configured macros can affect triggers in a template? 
There are literally 3 triggers inside a template.

**Comment by igorinsky** [comment]
Aha, you've been very helpful indeed.
So it's not in triggers, but in trigger_prorotypes and it requires a {$GROUPNAME}.

Thanks!

**Comment by tears-of-noobs** [comment]
@igorinsky Now this issue solved or not?
