### ISSUE TITLE
github.com/blacked/go-zabbix does not exist

### ISSUE THREAD

**Issue by zzjie871** [zarplata/zabbix-agent-extension-rabbitmq#15]
# make
Fetch dependencies
GO11MODULE=on go get
Build
GO11MODULE=on go build -v -o .out/zabbix-agent-extension-rabbitmq -ldflags "-X main.version="20190620.61_a9ef23e"" *.go
can't load package: /usr/lib/golang/src/zabbix-agent-extension-rabbitmq/main.go:9:2: non-standard import "github.com/blacked/go-zabbix" in standard package "zabbix-agent-extension-rabbitmq"
make: *** [build] Error 1

**Comment by tears-of-noobs** [comment]
@zzjie871 Hi. Which version of `golang` do  you use?

**Comment by grigribou** [comment]
Similar issue with golang version : go version go1.11.5 linux/amd64


Issue:

`
[root@coes16 zabbix-agent-extension-rabbitmq]# export GOPATH="/usr/lib/golang"
[root@coes16 zabbix-agent-extension-rabbitmq]# export GOBIN="/usr/lib/golang/bin/"
[root@coes16 zabbix-agent-extension-rabbitmq]# export PATH=$PATH:$GOBIN
[root@coes16 zabbix-agent-extension-rabbitmq]# pwd
/usr/lib/golang/src/zabbix-agent-extension-rabbitmq
[root@coes16 zabbix-agent-extension-rabbitmq]# make
Fetch dependencies
GO11MODULE=on go get
warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'
main.go:9:2: cannot find package "github.com/blacked/go-zabbix" in any of:
        /usr/lib/golang/src/vendor/github.com/blacked/go-zabbix (vendor tree)
        /usr/lib/golang/src/github.com/blacked/go-zabbix (from $GOROOT)
        ($GOPATH not set. For more details see: 'go help gopath')
main.go:10:2: cannot find package "github.com/docopt/docopt-go" in any of:
        /usr/lib/golang/src/vendor/github.com/docopt/docopt-go (vendor tree)
        /usr/lib/golang/src/github.com/docopt/docopt-go (from $GOROOT)
        ($GOPATH not set. For more details see: 'go help gopath')
discovery.go:7:2: cannot find package "github.com/michaelklishin/rabbit-hole" in any of:
        /usr/lib/golang/src/vendor/github.com/michaelklishin/rabbit-hole (vendor tree)
        /usr/lib/golang/src/github.com/michaelklishin/rabbit-hole (from $GOROOT)
        ($GOPATH not set. For more details see: 'go help gopath')
tools.go:14:2: cannot find package "github.com/reconquest/karma-go" in any of:
        /usr/lib/golang/src/vendor/github.com/reconquest/karma-go (vendor tree)
        /usr/lib/golang/src/github.com/reconquest/karma-go (from $GOROOT)
        ($GOPATH not set. For more details see: 'go help gopath')
make: *** [deps] Error 1
[root@coes16 zabbix-agent-extension-rabbitmq]# 
`

Thanks!

**Comment by grigribou** [comment]
Solved using "From source" installation method.
"Fom Centos 7" was now working for me

**Comment by YevgeniyYatsenko** [comment]
Hello.
Have the same error.  Did on instruction.

**Comment by tears-of-noobs** [comment]
@YevgeniyYatsenko @grigribou @zzjie871 Now it's should work. There was a error in environment variable naming in `Makefile`. Fetch the last changes and try again.

**Comment by YevgeniyYatsenko** [comment]
I use "From source: CentOS 7". When I`ve done "make", got message:

[root@host zabbix-agent-extension-rabbitmq]# make
Fetch dependencies
GO111MODULE=on go get
warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
Build
GO111MODULE=on go build -v -o .out/zabbix-agent-extension-rabbitmq -ldflags "-X main.version="20190909.62_426a42c"" *.go
warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
can't load package: /usr/lib/golang/src/zabbix-agent-extension-rabbitmq/main.go:9:2: non-standard import "github.com/blacked/go-zabbix" in standard package "zabbix-agent-extension-rabbitmq"
make: *** [build] Error 1

**Comment by tears-of-noobs** [comment]
@YevgeniyYatsenko Please show me outputs of `go env` and `go version`

**Comment by YevgeniyYatsenko** [comment]
[root@host zabbix-agent-extension-rabbitmq]# go env
warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
GOARCH="amd64"
GOBIN="/usr/lib/golang/bin/"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/lib/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build818972686=/tmp/go-build -gno-record-gcc-switches"
[root@host zabbix-agent-extension-rabbitmq]# go version
warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
go version go1.11.5 linux/amd64
[root@host zabbix-agent-extension-rabbitmq]#

**Comment by tears-of-noobs** [comment]
@YevgeniyYatsenko Why you have GOPATH set to the same path as GOROOT? Set it to your real developing directory, like `~/projects/go` or something else. I've just tested build inside pure golang container with 1.11.5 version onboard and I have no error.

```sh
❱ sudo docker run -u 0 -it --entrypoint sh golang:1.11.5-alpine
/go # apk add git musl-dev gcc make
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/20) Upgrading musl (1.1.20-r3 -> 1.1.20-r5)
(2/20) Installing binutils (2.31.1-r2)
(3/20) Installing gmp (6.1.2-r1)
(4/20) Installing isl (0.18-r0)
(5/20) Installing libgomp (8.3.0-r0)
(6/20) Installing libatomic (8.3.0-r0)
(7/20) Installing libgcc (8.3.0-r0)
(8/20) Installing mpfr3 (3.1.5-r1)
(9/20) Installing mpc1 (1.0.3-r1)
(10/20) Installing libstdc++ (8.3.0-r0)
(11/20) Installing gcc (8.3.0-r0)
(12/20) Installing nghttp2-libs (1.35.1-r1)
(13/20) Installing libssh2 (1.8.2-r0)
(14/20) Installing libcurl (7.64.0-r2)
(15/20) Installing expat (2.2.7-r0)
(16/20) Installing pcre2 (10.32-r1)
(17/20) Installing git (2.20.1-r0)
(18/20) Upgrading musl-utils (1.1.20-r3 -> 1.1.20-r5)
(19/20) Installing make (4.2.1-r2)
(20/20) Installing musl-dev (1.1.20-r5)
Executing busybox-1.29.3-r10.trigger
OK: 118 MiB in 33 packages
/go # cd /tmp
/tmp # git clone https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git
Cloning into 'zabbix-agent-extension-rabbitmq'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 286 (delta 10), reused 13 (delta 5), pack-reused 263
Receiving objects: 100% (286/286), 66.17 KiB | 564.00 KiB/s, done.
Resolving deltas: 100% (113/113), done.
/tmp # cd zabbix-agent-extension-rabbitmq/
/tmp/zabbix-agent-extension-rabbitmq # make
Fetch dependencies
GO111MODULE=on go get
go: finding github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: finding github.com/docopt/docopt-go v0.0.0-20160216232012-784ddc588536
go: finding github.com/onsi/ginkgo v1.8.0
go: finding github.com/blacked/go-zabbix v0.0.0-20170118040903-3c6a95ec4fdc
go: finding github.com/michaelklishin/rabbit-hole v1.5.0
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/reconquest/karma-go v0.0.0-20181113092637-e34418e5cfc5
go: finding github.com/onsi/gomega v1.5.0
go: finding github.com/onsi/ginkgo v1.6.0
go: finding github.com/hpcloud/tail v1.0.0
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/stretchr/objx v0.1.0
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/michaelklishin/rabbit-hole v1.5.0
go: downloading github.com/reconquest/karma-go v0.0.0-20181113092637-e34418e5cfc5
go: downloading github.com/docopt/docopt-go v0.0.0-20160216232012-784ddc588536
go: downloading github.com/blacked/go-zabbix v0.0.0-20170118040903-3c6a95ec4fdc
Build
GO111MODULE=on go build -v -o .out/zabbix-agent-extension-rabbitmq -ldflags "-X main.version="20190909.62_426a42c"" *.go
command-line-arguments
Done

```

**Comment by axlroden** [comment]
on your centos 7 from source help text, you are setting the GOPATH to the GOROOT, maybe thats what causing this confusion ? 
Also if people are on centos 6, then they need to get golang 1.12 from source, as the yum package is 1.11

**Comment by tears-of-noobs** [comment]
@axlroden Оh, i see, of course it's a mistake, thanks for your attention on it I'll fix it ASAP. About Go version - you can compile this extension using Go 1.11, it not necessary to build 1.12.

**Comment by axlroden** [comment]
hmm ok, I had issues on 1.11, but worked great on 1.12
