### ISSUE TITLE
trap failed from zabbix side

### ISSUE THREAD

**Issue by grigribou** [zarplata/zabbix-agent-extension-rabbitmq#16]
Hi,

I'm trying to use this extension but I have an issue.
Zabbix receive json message with values, but as failed.

I did a test with file input in zabbix_sender, for sending several values and it's OK.

I also tryed to send manually a avlue from json file and it's OK:
`[root@coes16 tmp]# zabbix_sender -z 10.107.0.49 -s coes16 -k rabbitmq.queue.messages_unacknowledged[/,email.in.manual] -o 9999999
info from server: "processed: 1; failed: 0; total: 1; seconds spent: 0.000045"
sent: 1; skipped: 0; total: 1
`

I have issue only this this extention, and i'm not able to find root cause of error.

I did several tcpdump to check outgoing messages

**With zabbix sender:**
![image](https://user-images.githubusercontent.com/8124469/64488094-e2ba1b00-d243-11e9-81dd-a5c88efffec7.png)

**With extension:**
![image](https://user-images.githubusercontent.com/8124469/64488100-f82f4500-d243-11e9-8e2c-3e70ed81f178.png)

Some one have an idea?

**Comment by tears-of-noobs** [comment]
@grigribou Hi. The host which you monitor has the name - 'coes06' on `zabbix server`?

**Comment by grigribou** [comment]
Right! 
My mistake!! 
Sorry!!
