### ISSUE TITLE
working without CA?

### ISSUE THREAD

**Issue by YevgeniyYatsenko** [zarplata/zabbix-agent-extension-rabbitmq#17]
zabbix-agent-extension-rabbitmq could work without CA? Because my rabbitmq hasn`t SSL.

[root@host zabbix_agentd.d]# cat zabbix-agent-extension-rabbitmq.conf
UserParameter=rabbitmq.discovery[*], /usr/bin/zabbix-agent-extension-rabbitmq --discovery --rabbitmq $1 --rabbitmq-user $2 --rabbitmq-secret $3 --ca $4
UserParameter=rabbitmq.aggregate.discovery[*], /usr/bin/zabbix-agent-extension-rabbitmq --discovery --aggregate --group $1 --rabbitmq $2 --rabbitmq-user $3 --rabbitmq-secret $4 --ca $5
UserParameter=rabbitmq.stats[*], /usr/bin/zabbix-agent-extension-rabbitmq --zabbix $1 --rabbitmq $2 --rabbitmq-user $3 --rabbitmq-secret $4 --ca $5 --hostname $6

[root@host zabbix_agentd.d]# zabbix_agentd -t rabbitmq.discovery[10.10.5.57:15762,user,pass]
rabbitmq.discovery[10.10.5.57:15762,user,pass] [t|--ca requires argument
Usage:
    zabbix-agent-extension-rabbitmq [-r <address>] [-u <name>] [-s <password>] [-t <timeout>] [-c <path>] [-z <host>] [-p <number>] [-o <name>] [-d [-g <name>] [-a]]]

[root@host zabbix_agentd.d]# zabbix_agentd -t rabbitmq.discovery[10.10.5.57:15762,user,pass,]
rabbitmq.discovery[10.10.5.57:15762,user,pass,] [t|--ca requires argument
Usage:
    zabbix-agent-extension-rabbitmq [-r <address>] [-u <name>] [-s <password>] [-t <timeout>] [-c <path>] [-z <host>] [-p <number>] [-o <name>] [-d [-g <name>] [-a]]]

[root@host zabbix_agentd.d]# zabbix_agentd -t rabbitmq.discovery[10.10.5.57:15762,user,pass,,]
rabbitmq.discovery[10.10.5.57:15762,user,pass,,] [t|--ca requires argument
Usage:
    zabbix-agent-extension-rabbitmq [-r <address>] [-u <name>] [-s <password>] [-t <timeout>] [-c <path>] [-z <host>] [-p <number>] [-o <name>] [-d [-g <name>] [-a]]]

**Comment by tears-of-noobs** [comment]
@YevgeniyYatsenko Yes, CA is optionally argument and by default it sets to 'None' value at https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/main.go#L30 it means that extension will use HTTP transport instead HTTPS. And as I see, you're trying to execute extension manually, you shouldn't do that because some default values placed in the template, and you should use call from `zabbix server` instead manually run.

**Comment by YevgeniyYatsenko** [comment]
Disadvantage I can not get some data in my zabbix-server after install plugin "zabbix-agent-extension-rabbitmq".
My steps:
1. Executed instructuion "Instalation From source" successfully
2. Added template to zabbix-server.
3. Activated rabbit management Plugin in my docker rabbit container by command "rabbitmq-plugins enable rabbitmq_management"
4. Create user user/pass with permition "monitoring"
5. Added global macros in zabbix server.
- {$RABBITMQ_CA_PATH} => None
- {$RABBITMQ_MGMT_ADDRESS} = > 10.10.5.57:15672
- {$RABBITMQ_PASSWORD} => pass
- {$RABBITMQ_USER} => user
- {$RABBITMQ_PORT} = > 15672
- {$ZABBIX_SERVER_IP} = > 10.10.5.55
6. Reboox zabbix-agent on target host

But I can not get some data in my zabbix server. What do I do wrong? Could you help me?

**Comment by tears-of-noobs** [comment]
@YevgeniyYatsenko 
1. Check that you have discovered items in your web interface.
2. Check the value of `RabbitMQ stats` item, in normal it should be - `OK`
3. Ensure that hostname on host with rabbitmq and extension is equal with hostname in zabbix server.

**Comment by tears-of-noobs** [comment]
@YevgeniyYatsenko I've closed the issue because you didn't leave feedback to my previous comment, seems you solve your problem. If the problem still actual - reopen the issue.
