### ISSUE TITLE
RabbitMQ process is NOT running even when the Rabbit is Up

### ISSUE THREAD

**Issue by Genacvali** [zarplata/zabbix-agent-extension-rabbitmq#18]
Hello,

We implemented the template for RabbitMQ to our zabbix monitoring
Zabbix 4+
Rabbit 3.7.17Erlang 22.0.7

Could you pleae assist? And please let me know if any additional info are require from our side.

Thank You

**Comment by tears-of-noobs** [comment]
@Genacvali Hello. Something wrong with the extension, or an error occurs? You don't see items or metrics? I can't figure out a problem with your issue description, please provide a little bit more information.

**Comment by Genacvali** [comment]
Hello
There wer emy mistake with configurations
Sorry
Closing this issue
