### ISSUE TITLE
Правила обнаружения Нет такого файла или каталога

### ISSUE THREAD

**Issue by DishinIR** [zarplata/zabbix-agent-extension-rabbitmq#22]
Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: /usr/bin/zabbix-agent-extension-rabbitmq: Нет такого файла или каталога' Подскажите пож-та как настроить что сделал не так?

**Comment by tears-of-noobs** [comment]
@DishinIR Hi. First, tell me about your installation of the extension. How did you install it? As far as I see - you have add RabbitMQ template into your `Zabbix server` but didn't install the extension binary on the target node, where RabbitMQ runs.

**Comment by DishinIR** [comment]
Все сделал по данной инструкции https://github.com/zarplata/zabbix-agent-extension-rabbitmq. Путь  /usr/bin/zabbix-agent-extension-rabbitmq скопировал файл в ручную и установил zabbix agent где работает RabbitMQ

**Comment by DishinIR** [comment]
Пробовали сами выполнить по данным настройкам? 
From source: CentOS 7
yum install go -y

# Create directory for development
mkdir -p /home/USERNAME/golang/{pkg,src,bin}
# export GOPATH variable
export GOPATH="/home/USERNAME/golang"
export PATH=$PATH:$GOPATH/bin

# Clone the repository
cd /tmp/
git clone https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git

# Build
cd zabbix-agent-extension-rabbitmq/
make

# Install
cp .out/zabbix-agent-extension-rabbitmq /usr/bin/
cp zabbix-agent-extension-rabbitmq.conf /etc/zabbix/zabbix_agentd.d/
systemctl restart zabbix-agent.service

**Comment by tears-of-noobs** [comment]
@DishinIR Can you manually run the extension? 
`/usr/bin/zabbix-agent-extension-rabbitmq --discovery` And tell me about your environment. Do you trying to run the extension on bare-metal host or inside Docker container?

**Comment by DishinIR** [comment]
нет не могу запустить. Нужно редактировать файл /usr/bin/zabbix-agent-extension-rabbitmq.conf ?

**Comment by DishinIR** [comment]
Когда имеется кластер нужно в каждый узел добавлять шаблон?

**Comment by tears-of-noobs** [comment]
@DishinIR But file exists? Check file mode of the extension `stat /usr/bin/zabbix-agent-extension-rabbitmq`. It should be - `0755`

**Comment by DishinIR** [comment]
да 0755

**Comment by DishinIR** [comment]
Теперь Zabbix выдает ошибку Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: /usr/bin/zabbix-agent-extension-rabbitmq: Это каталог

**Comment by tears-of-noobs** [comment]
@DishinIR I can't understand whats going wrong. Let's start from the beginning.
1) Can you run extension manually `/usr/bin/zabbix-agent-extension-rabbitmq --discovery`. If you can - do it and tell me what you see on output. If you can't - tell me the error, or something reason why you can't.
2) Show me the `stat /usr/bin/zabbix-agent-extension-rabbitmq`

**Comment by DishinIR** [comment]
1. [root@RabbitTBS ~]# /usr/bin/zabbix-agent-extension-rabbitmq --discovery
-bash: /usr/bin/zabbix-agent-extension-rabbitmq: Это каталог
2.[root@RabbitTBS ~]# stat /usr/bin/zabbix-agent-extension-rabbitmq
  Файл: «/usr/bin/zabbix-agent-extension-rabbitmq»
  Размер: 4096          Блоков: 8          Блок В/В: 4096   каталог
Устройство: fd00h/64768d        Inode: 150626      Ссылки: 3
Доступ: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Контекст: unconfined_u:object_r:admin_home_t:s0
Доступ: 2019-10-14 10:44:27.120748934 +0300
Модифицирован: 2019-06-10 10:24:14.433366392 +0300
Изменён: 2019-10-14 10:42:26.383448870 +0300
 Создан: -

**Comment by tears-of-noobs** [comment]
@DishinIR And why it's a directory? It should be a binary file. You made an error when you was doing copy the extension. After `make` command you should see a binary in `.out/` directory.
From README
```
git clone https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git
cd zabbix-agent-extension-rabbitmq/
make
cp .out/zabbix-agent-extension-rabbitmq /usr/bin/
```

**Comment by DishinIR** [comment]
[root@RabbitTBS ~]# git clone https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git
Cloning into 'zabbix-agent-extension-rabbitmq'...
fatal: unable to access 'https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git/': Operation timed out after 300040 milliseconds with 0 out of 0 bytes received

Через веб-браузер открывается данная ссылка

**Comment by DishinIR** [comment]
пробую так 
[root@RabbitTBS ~]# cd /usr/bin/
[root@RabbitTBS bin]# cd zabbix-agent-extension-rabbitmq/
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# make
Clean dependencies
rm -rf vendor/*
Clean builded binaries
rm -rf .out/
Done
Fetch dependencies
dep ensure -v
make: dep: Команда не найдена
make: *** [deps] Ошибка 127
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# cp .out/zabbix-agent-extension-rabbitmq /usr/bin/
cp: не удалось выполнить stat для «.out/zabbix-agent-extension-rabbitmq»: Нет такого файла или каталога

**Comment by tears-of-noobs** [comment]
@DishinIR As far as I see - you have a problem with internet connection from `RabbitTBS` host, check your firewall rules or something. About your the second problem - you trying to build previous version of the extension which based on `dep` dependency manager and  you have not installed it. As a told you earlier - you have a problem with internet connection from your host to `github`, solve it, then clone latest version from repository and build it.

**Comment by DishinIR** [comment]
по указанному сайту git clone https://github.com/zarplata/zabbix-agent-extension-rabbitmq.git не получается, нет других аналогов?

**Comment by tears-of-noobs** [comment]
@DishinIR Nope, but you can make an effort to build extension on your local machine through Docker, then perform a copy through `scp` to target machine `RabbitTBS`

**Comment by tears-of-noobs** [comment]
@DishinIR I've close the issue because there aren't any problem with the extension.

**Comment by DishinIR** [comment]
при выполнение make 
go: gopkg.in/yaml.v2@v2.2.1: unknown revision v2.2.1
go: golang.org/x/text@v0.3.0: unknown revision v0.3.0
go: gopkg.in/fsnotify.v1@v1.4.7: unknown revision v1.4.7
go: golang.org/x/net@v0.0.0-20180906233101-161cd47e91fd: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
        fatal: unable to connect to go.googlesource.com:
        go.googlesource.com[0: 64.233.165.82]: errno=????? ???????? ?????????? ???????
        go.googlesource.com[1: 2a00:1450:4010:c08::52]: errno=???? ??????????
go: golang.org/x/sys@v0.0.0-20180909124046-d0be0721c37e: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/76a8992ccba6d77c6bcf031ff2b6d821cf232e4ad8d1f2362404fbd0a798d846: exit status 128:
        fatal: unable to connect to go.googlesource.com:
        go.googlesource.com[0: 64.233.165.82]: errno=????? ???????? ?????????? ???????
        go.googlesource.com[1: 2a00:1450:4010:c08::52]: errno=???? ??????????
go: gopkg.in/tomb.v1@v1.0.0-20141024135613-dd632973f1e7: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/95acae1f863cd3698780e83ddc42f6ad6cd0ab1cb79143808a7de7300ae4df93: exit status 128:
        fatal: unable to connect to gopkg.in:
        gopkg.in[0: 35.196.143.184]: errno=????? ???????? ?????????? ???????
go: golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/55179c5d8c4db2eaed9fae4682d4c84a1fd3612df666b372bef3bbb997c9601f: exit status 128:
        fatal: unable to connect to go.googlesource.com:
        go.googlesource.com[0: 64.233.165.82]: errno=????? ???????? ?????????? ???????
        go.googlesource.com[1: 2a00:1450:4010:c08::52]: errno=???? ??????????
go: error loading module requirements
make: *** [deps] Ошибка 1

**Comment by DishinIR** [comment]
cp .out/zabbix-agent-extension-rabbitmq /usr/bin/
cp: не удалось выполнить stat для «.out/zabbix-agent-extension-rabbitmq»: Нет такого файла или каталога

**Comment by DishinIR** [comment]
Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Usage: zabbix-agent-extension-rabbitmq [-r <address>] [-u <name>] [-s <password>] [-t <timeout>] [-c <path>] [-z <host>] [-p <number>] [-o <name>]

**Comment by tears-of-noobs** [comment]
@DishinIR Can you invoke the extension manually? `/usr/bin/zabbix-agent-exetension-rabbimq --discovery` 
Also show me the output of `/usr/bin/zabbix-agent-extension-rabbitmq --help` and content of the agent configuration `cat /etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-rabbitmq.conf`

**Comment by DishinIR** [comment]
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# cat /etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-rabbitmq.conf
UserParameter=rabbitmq.discovery[*], /usr/bin/zabbix-agent-extension-rabbitmq --discovery --rabbitmq $1 --rabbitmq-user $2 --rabbitmq-secret $3 --ca $4
UserParameter=rabbitmq.aggregate.discovery[*], /usr/bin/zabbix-agent-extension-rabbitmq --discovery --aggregate --group $1 --rabbitmq $2 --rabbitmq-user $3 --rabbitmq-secret $4 --ca $5
UserParameter=rabbitmq.stats[*], /usr/bin/zabbix-agent-extension-rabbitmq --zabbix $1 --rabbitmq $2 --rabbitmq-user $3 --rabbitmq-secret $4 --ca $5 --hostname $6

**Comment by DishinIR** [comment]
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# /usr/bin/zabbix-agent-exetension-rabbimq --discovery
-bash: /usr/bin/zabbix-agent-exetension-rabbimq: Нет такого файла или каталога

**Comment by DishinIR** [comment]
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# /usr/bin/zabbix-agent-extension-rabbitmq --help
zabbix-agent-extension-rabbitmq

Usage:
    zabbix-agent-extension-rabbitmq [-r <address>] [-u <name>] [-s <password>] [-t <timeout>] [-c <path>] [-z <host>] [-p <number>] [-o <name>] [-d [-g <name>] [-a]]

RabbitMQ options:
    -r --rabbitmq <address>          Listen address of RabbitMQ server [default: http://127.0.0.1:15672]
    -u --rabbitmq-user <name>        RabbitMQ management username [default: guest]
    -s --rabbitmq-secret <password>  RabbitMQ management password [default: guest]
    -t --rabbitmq-timeout <timeout>  RabbitMQ request timeout in ms [default: 5000ms]
    -c --ca <path>                   Path to CA file. [default: None]

Zabbix options:
    -z --zabbix <host>               Hostname or IP address of Zabbix server [default: 127.0.0.1]
    -p --zabbix-port <number>        Port of Zabbix server [default: 10051]
    -d --discovery                   Run low-level discovery for determine queues, exchanges, etc.
    -a --aggregate                   Discovery aggregate items.
    -g --group <name>                Group name which will be use for aggregate item values.[default: None]
    -o --hostname <name>             Hostname which will be used in zabbix-sender protocol data. [default: RabbitTBS]

Misc options:
    -h --help                        Show this screen.
    -v --version                     Show version.

**Comment by DishinIR** [comment]
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# /usr/bin/zabbix-agent-extension-rabbitmq --discovery
{"data":[{"{#QUEUENAME}":"TBN_Itil","{#VHOST}":"/"},{"{#QUEUENAME}":"TBS_00001_Zup_Doc","{#VHOST}":"/"},{"{#QUEUENAME}":"TBS_00002_Doc_Zup","{#VHOST}":"/"},{"{#QUEUENAME}":"TBS_00003_Doc_Zup","{#VHOST}":"/"},{"{#QUEUENAME}":"TBS_Doc_TBN_Itil","{#VHOST}":"/"},{"{#QUEUENAME}":"TST_00001","{#VHOST}":"/"},{"{#QUEUENAME}":"TST_00002","{#VHOST}":"/"},{"{#QUEUENAME}":"TST_00003","{#VHOST}":"/"},{"{#QUEUENAME}":"TST_00004","{#VHOST}":"/"},{"{#QUEUENAME}":"TST_ASU_001","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasRS_Tagras_TenderProtocol","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_PCT_PutList","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_PCT_Request","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_PCT_TTD","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_Registry","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_Status","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_StatusRegistry_PST","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_StatusTTD_PCT","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TS","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TST_PutList","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TST_Request","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TST_TTD","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TTC_PutList","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TTC_Request","{#VHOST}":"/"},{"{#QUEUENAME}":"TagrasTransport_TTC_TTD","{#VHOST}":"/"},{"{#QUEUENAME}":"Tatinek_UPP_Kontragents","{#VHOST}":"/"},{"{#QUEUENAME}":"Tatintek_UDD_Contracts","{#VHOST}":"/"},{"{#QUEUENAME}":"rmq.demo-incoming-calls","{#VHOST}":"/"},{"{#QUEUENAME}":"rpc.rmq.demo-incoming-calls","{#VHOST}":"/"},{"{#QUEUENAME}":"tbs_test","{#VHOST}":"/"}]}

**Comment by DishinIR** [comment]
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# /usr/bin/zabbix-agent-extension-rabbitmq --help
zabbix-agent-extension-rabbitmq

Usage:
    zabbix-agent-extension-rabbitmq [-r <address>] [-u <name>] [-s <password>] [-t <timeout>] [-c <path>] [-z <host>] [-p <number>] [-o <name>] [-d [-g <name>] [-a]]

RabbitMQ options:
    -r --rabbitmq <address>          Listen address of RabbitMQ server [default: http://127.0.0.1:15672]
    -u --rabbitmq-user <name>        RabbitMQ management username [default: guest]
    -s --rabbitmq-secret <password>  RabbitMQ management password [default: guest]
    -t --rabbitmq-timeout <timeout>  RabbitMQ request timeout in ms [default: 5000ms]
    -c --ca <path>                   Path to CA file. [default: None]

Zabbix options:
    -z --zabbix <host>               Hostname or IP address of Zabbix server [default: 127.0.0.1]
    -p --zabbix-port <number>        Port of Zabbix server [default: 10051]
    -d --discovery                   Run low-level discovery for determine queues, exchanges, etc.
    -a --aggregate                   Discovery aggregate items.
    -g --group <name>                Group name which will be use for aggregate item values.[default: None]
    -o --hostname <name>             Hostname which will be used in zabbix-sender protocol data. [default: RabbitTBS]

Misc options:
    -h --help                        Show this screen.
    -v --version                     Show version.

**Comment by DishinIR** [comment]
[root@RabbitTBS zabbix-agent-extension-rabbitmq]# cat /etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-rabbitmq.conf
UserParameter=rabbitmq.discovery[*], /usr/bin/zabbix-agent-extension-rabbitmq --discovery --rabbitmq $1 --rabbitmq-user $2 --rabbitmq-secret $3 --ca $4
UserParameter=rabbitmq.aggregate.discovery[*], /usr/bin/zabbix-agent-extension-rabbitmq --discovery --aggregate --group $1 --rabbitmq $2 --rabbitmq-user $3 --rabbitmq-secret $4 --ca $5
UserParameter=rabbitmq.stats[*], /usr/bin/zabbix-agent-extension-rabbitmq --zabbix $1 --rabbitmq $2 --rabbitmq-user $3 --rabbitmq-secret $4 --ca $5 --hostname $6

**Comment by DishinIR** [comment]
> @DishinIR Можете ли вы вызвать расширение вручную? `/usr/bin/zabbix-agent-exetension-rabbimq --discovery`
> Также покажите мне вывод `/usr/bin/zabbix-agent-extension-rabbitmq --help`и содержание конфигурации агента`cat /etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-rabbitmq.conf`

Отправил Вам посмотрите пож-та.

**Comment by tears-of-noobs** [comment]
@DishinIR I guess your setup of the extension is misconfigured, because I can't figure out whats wrong in this case. As far as I see - extension on the `zabbix agent` side works properly and you receive JSON with discovered queues, but you have an error on the `zabbix server` side. You should check configuration on the `Zabbix server` side (items configuration in template).

**Comment by DishinIR** [comment]
> @DishinIR Я думаю, что ваша установка расширения неправильно настроена, потому что я не могу понять, что не так в этом случае. Насколько я вижу - расширение на `zabbix agent`стороне работает правильно, и вы получаете JSON с обнаруженными очередями, но у вас есть ошибка на `zabbix server`стороне. Вы должны проверить конфигурацию на `Zabbix server`стороне (элементы конфигурации в шаблоне).

/etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-rabbitmq.conf нужно ли редактировать данный файл ?

**Comment by tears-of-noobs** [comment]
@DishinIR No. I've check template file and agent configuration and [item in the template](https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/template_app_rabbitmq_service.xml#L766) corresponds with the `UserParameter` definition in the [agent configuration](https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/zabbix-agent-extension-rabbitmq.conf#L1) Try to re-import the template, and replace agent configuration from `master` branch then restart agent.

**Comment by DishinIR** [comment]
> @DishinIR Нет. Я проверил файл шаблона и конфигурацию агента, и [элемент в шаблоне](https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/template_app_rabbitmq_service.xml#L766) Соответствует `UserParameter`определению в [конфигурации Агента. ](https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/zabbix-agent-extension-rabbitmq.conf#L1)Попробуйте повторно импортировать шаблон и заменить конфигурацию агента из `master`ветви.

Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Get http://127.0.0.1:15672/api/vhosts: dial tcp 127.0.0.1:15672: connect: permission denied'

**Comment by DishinIR** [comment]
> @DishinIR No. I've check template file and agent configuration and [item in the template](https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/template_app_rabbitmq_service.xml#L766) corresponds with the `UserParameter` definition in the [agent configuration](https://github.com/zarplata/zabbix-agent-extension-rabbitmq/blob/master/zabbix-agent-extension-rabbitmq.conf#L1) Try to re-import the template, and replace agent configuration from `master` branch then restart agent.

похоже с кластеризацией не правильно настройки производим.

**Comment by tears-of-noobs** [comment]
@DishinIR You have an error - `dial tcp 127.0.0.1:15672: connect: permission denied` it's not a extension problem it's a problem with your configuration of RabbitMQ or RabbitMQ management plugin or your host/firewall where extension runs. Please check out the official documentation of RabbitMQ management plugin and review your configuration.

**Comment by tears-of-noobs** [comment]
@DishinIR The extension should work properly on the default configuration of RabbitMQ with management plugin. If you have any customization on your setup of the extension or any firewall rule or any permission setting based on you security policy - you should accordingly configure the extension too.

**Comment by DishinIR** [comment]
У нас 2 RabbitMQ макросы наследованные в каждом.  {$GROUPNAME} = rabbitmq_aggregate именно так указывать нужно в каждом?

**Comment by tears-of-noobs** [comment]
@DishinIR Read the Readme, there is an information about it.
