### ISSUE TITLE
Error 401 (not_authorised): Login failed

### ISSUE THREAD

**Issue by TheB8mb** [zarplata/zabbix-agent-extension-rabbitmq#3]
Hello people,

Thanks for this extension, it works great on our staging env. 
I'm at a loss when it comes to prod env though, since the RabbitMQ stats item is getting an "Error 401 (not_authorised): Login failed" and RabbitMQ process num shows 0.

I'm not quite sure if I've missed anything but any insights or tips would be much appreciated!

**Comment by tears-of-noobs** [comment]
@TheB8mb Hi. Could you re-import Zabbix template from repository `template_app_rabbitmq_service.xml` and replace Zabbix agent configuration `zabbix-agent-extension-rabbitmq.conf` I've made a little bit improvement and now you can change both username and password through the template macros `{$RABBIMQ_USER}` and `{$RABBITMQ_PASSWORD}`

**Comment by TheB8mb** [comment]
@tears-of-noobs Hey, I tried re-importing the Zabbix Template `template_app_rabbitmq_service.xml` but failed with error:

> Incorrect item key "rabbitmq.stats[{$ZABBIX_SERVER_IP}]" provided for trigger expression on "Template App Rabbitmq Service".

I changed the line #1369 to:
`<expression>{Template App Rabbitmq Service:rabbitmq.stats[{$ZABBIX_SERVER_IP},{$RABBITMQ_USER},{$RABBITMQ_PASSWORD}].regexp(OK)}=0</expression>`

which did the trick.

**Comment by TheB8mb** [comment]
Just noticed I accidentally closed this. Sorry.
Same error occurs:

> Error 401 (not_authorised): Login failed

I have changed the user on rabbitmq ui like below and I'm not quite sure what expression for permissions should be used:

Virtual host | Configure regexp | Write regexp | Read regexp |  
/                  |              '^$'          |         '^$'       |            .*

**Comment by tears-of-noobs** [comment]
Did you replace extension config and restart zabbix-agent? As I see, there may be two problems:

- The extension doesn't receive credentials from Zabbix server
- RabbitMQ server doesn't allow remote connection. Access control rules describe here - https://www.rabbitmq.com/access-control.html

**Comment by TheB8mb** [comment]
Hello again,
I've managed to get it down to 2 probable "blockers":
1) Is internet access absolutely needed for the extension to work, and
2) Is PSK encryption on host and client supported

**Comment by tears-of-noobs** [comment]
@TheB8mb Hi
1) No. Extension no needs internet access if you have a private network and all of your services run inside it without communication through the internet.

2) What do you mean? As I know, management plugin supports communication over HTTPS and  I've added it by this commit https://github.com/zarplata/zabbix-agent-extension-rabbitmq/commit/b3e9139d60180ed57fa00aa9f435eaa0ee811797

**Comment by igorinsky** [comment]
JFYI: Had the same error, which was fixed by adding more permissions to rabbit user - he should has access to / , not only to special vhosts.
