### ISSUE TITLE
Missing macros

### ISSUE THREAD

**Issue by cmmata** [zarplata/zabbix-agent-extension-rabbitmq#4]
Hello!

I'm configuring this template, and I think the docs need to say that you have to create 3 more macros: `{$RABBITMQ_USER}`, `{$RABBITMQ_PORT}` and `{$RABBITMQ_PASSWORD}`. Or am I missing any previous step?

**Comment by tears-of-noobs** [comment]
Hi @cmmata . Yep, you're right.  This commit https://github.com/zarplata/zabbix-agent-extension-rabbitmq/commit/b2471937804aefda06cc4bdfe70a2c4b282179fe resolves your issue
