### ISSUE TITLE
vhosts

### ISSUE THREAD

**Issue by wfeddern** [zarplata/zabbix-agent-extension-rabbitmq#6]
We have a number of queues in seperate vhosts, some with the same queue name. It seems that this is ignoring the vhosts, so we get errors during discovery of duplicate queue names. As well, we need the vhost name in any alerts to know which vhost/queue is alerting.

**Comment by tears-of-noobs** [comment]
@wfeddern Hi. I implemented `vhosts` support, try out the last commit from the master branch.

**Comment by wfeddern** [comment]
Thanks for the quick response on this. I have attached a pic showing a sample of what I am seeing now on autodiscovery for one of my queues. Looks like its not parsing the vhost name, and is duplicating the items with and without the vhost info. It is also not creating the triggers for the queues.

![Capture](https://user-images.githubusercontent.com/29799608/56301075-149bdb00-6105-11e9-9811-089fcbdc4ee0.JPG)

**Comment by tears-of-noobs** [comment]
Looks strange. As if no one vhost has been discovered. Try to execute manually the following command
```sh
/usr/bin/zabbix-agent-extension-rabbitmq --discovery --rabbitmq http://RMQ_ADDRESS:15672 --rabbitmq-user USERNAME --rabbitmq-secret PASSWORD --ca None
```
The output should be JSON with discovered vhosts and queues. 
For example:
```js
{"data":[{"{#QUEUENAME}":"api.events","{#VHOST}":"/"},......]}
```

**Comment by wfeddern** [comment]
Ok, found issue with my update (missed prompt to overwrite previous version when doing copies). Once that was done, your above command returns vhost info now and item creation looks better. I am not seeing any triggers. Should they be created based on the value I have in {$MAX_MESSAGES} macro?

I also see some errors on the discovery rules, which seem to match up to the queue names that exist in more then one vhost.
![Capture](https://user-images.githubusercontent.com/29799608/56309695-0f945700-6118-11e9-8a6f-094bf88216f1.JPG)

**Comment by tears-of-noobs** [comment]
Triggers create only on aggregate items, the second discovery rule has 3 trigger prototype. Have you clustered setup or only one RabbitMQ node?

Errors happened because import operation didn't re-create a template it updates the existing template. Look at the screen, you have 26 item prototypes old (without vhost) and new prototypes. Try to remove the existing template and import it again.

**Comment by wfeddern** [comment]
I am using clustered setup.
Things seem better once I made sure to remove template completely before re-adding. I also created aggregate host group and added macro as per your documentation for clusters.

It looks like it created the triggers this time on the aggregate items, but for some reason I am not getting any data points for any of the metrics.  Is there something I can run on the system with the agent installed to diagnose why it is not sending updates/data back to the zabbix server?

**Comment by tears-of-noobs** [comment]
@wfeddern You can use `ngrep` for viewing network data for a specific port. For example - `ngrep -d any port 10051`.  As a result, you should see the following data
```
T 172.16.194.187:53958 -> 172.16.163.35:10051 [A] #14
  ZBXD.y&......{"request":"sender data","data":[{"host":"HOSTNAME_AS_IN_ZABBIX","key":"rabbitmq.queue.node[/,api.events]","value":"rabbitmq@node","clock":1556000289},
```
Be sure that `HOSTNAME_AS_IN_ZABBIX` correspond with hostname in your Zabbix server.

**Comment by wfeddern** [comment]
That seems to be the issue. 
host: is using rabbitmq.domain.net, even though I have set in the zabbix agent config file:
Hostname=rabbitmq
and on Zabbix server, the host is defined as 'rabbitmq'
Is there somewhere it would be overriding the zabbix agent config?

**Comment by tears-of-noobs** [comment]
The extension doesn't use `zabbix-agent` configuration and `zabbix-sender` binary. It implements `zabbix-sender` protocol and takes hostname from your machine where it runs. Check out my last commit - https://github.com/zarplata/zabbix-agent-extension-rabbitmq/commit/a359106a5914b9623e707d6d85205299db133dcf I've added the feature to make possible to change hostname by argument. By default, the extension will use hostname from `{HOST.HOST}` macros. You should make full reinstall of the extension to use this feature.

**Comment by wfeddern** [comment]
Thanks for the update, but in the end I just updated the host entry in zabbix to use the FQDN and that resolved the issue. Once that was done I started getting data points, and the aggregate triggers are alerting where they should be.

**Comment by tears-of-noobs** [comment]
@wfeddern If the issue solved please close it.
